CREATE TABLE "FACTURAS"(
 
"INVOICE" CHAR(7) NOT NULL ,
 
"XML_URL" VARCHAR(255),
 
"PDF_URL" VARCHAR(255),
 
"FECHA_TIMBRE" DATETIME,
 
"UUID_CFDI" CHAR(36));

CREATE TABLE "CFDI_C_CLAVEPRODSERV"(
 "CLAVEPRODSERV" CHAR(8),
 "DESCRPCION" CHAR(100));

CREATE TABLE "CFDI_C_CLAVEUNIDAD"(
 "CLAVEUNIDAD" CHAR(50),
 "NOMBRE" CHAR(100));

CREATE TABLE "CFDI_C_CODIGOPOSTAL"(
 "CODIGO_POSTAL" CHAR(5),
 "ESTADO" CHAR(3),
 "MUNICIPIO" CHAR(3),
 "LOCALIDAD" CHAR(3));

CREATE TABLE "CFDI_C_PAIS"(
 "C_PAIS" CHAR(3),
 "DESCRIPCION" CHAR(50));

CREATE TABLE "CFDI_UM_SAT"(
 "Unit_Measure" CHAR(2) NOT NULL ,
 "CLAVEUNIDAD" CHAR(3));

CREATE TABLE "CFDI_INVMSTRFORM"(
 "PART" CHAR(23) NOT NULL ,
 "CLAVEPRODSERV" CHAR(8));

CREATE TABLE "CFDI_C_ESTADO"(
 "ESTADO" CHAR(3),
 "PAIS" CHAR(3),
 "NOMBRE_ESTADO" CHAR(50));

CREATE TABLE "CFDI_DIRECCION"(
 "CUSTOMER" CHAR(6) NOT NULL ,
 "CODIGO_POSTAL" CHAR(5),
 "PAIS" CHAR(3),
 "ESTADO" CHAR(50));

CREATE UNIQUE INDEX "CFDI_DIRECCIONK00" USING 0 ON "CFDI_DIRECCION"("CUSTOMER", "CODIGO_POSTAL", "PAIS");
CREATE INDEX "CFDI_DIRECCIONK003" USING 3 ON "CFDI_DIRECCION"("CUSTOMER", "ESTADO");
CREATE UNIQUE INDEX "CFDI_DIRECCIONK01" USING 1 ON "CFDI_DIRECCION"("CUSTOMER", "CODIGO_POSTAL");
CREATE UNIQUE INDEX "CFDI_DIRECCIONK02" USING 2 ON "CFDI_DIRECCION"("CUSTOMER", "PAIS");

CREATE UNIQUE INDEX "CFDI_C_ESTADOK00" USING 0 ON "CFDI_C_ESTADO"("ESTADO");

CREATE INDEX AR_OPEN_ITEMSK05 ON AR_OPEN_ITEMS(ORDER_NO);
CREATE UNIQUE INDEX "CFDI_DIRECCIONK02" USING 2 ON "CFDI_DIRECCION"("CUSTOMER", "PAIS");
CREATE UNIQUE INDEX "CFDI_CLAVEPRODSERK00" ON "CFDI_C_CLAVEPRODSERV"("CLAVEPRODSERV", "DESCRPCION");
CREATE UNIQUE INDEX "CFDI_INVMSTRFORMK00" USING 0 ON "CFDI_INVMSTRFORM"("part", "CLAVEPRODSERV");
CREATE INDEX "CFDI_CLAVEUNIDADK00" ON "CFDI_C_CLAVEUNIDAD"("CLAVEUNIDAD", "NOMBRE");
CREATE INDEX "CFDI_CODIGOPOSTALK00" ON "CFDI_C_CODIGOPOSTAL"("CODIGO_POSTAL", "ESTADO", "MUNICIPIO");
CREATE INDEX "CFDI_PAISK00" ON "CFDI_C_PAIS"("C_PAIS", "DESCRIPCION");
CREATE UNIQUE INDEX "CFDI_UM_SAT" USING 0 ON "CFDI_UM_SAT"("Unit_Measure", "CLAVEUNIDAD");


CREATE TABLE "CFDI_COMEXTCOMPANY"(
 "NAME_COMPANY" CHAR(100) NOT NULL ,
 "RFC" CHAR(16),
 "CALLE" CHAR(100),
 "NUM_EXTERIOR" CHAR(50),
 "NUM_INTERIOR" CHAR(50),
 "CODIGO_POSTAL" CHAR(5),
 "COLONIA" CHAR(5),
 "LOCALIDAD" CHAR(2),
 "MUNICIPIO" CHAR(3),
 "ESTADO" CHAR(3),
 "PAIS" CHAR(3),
 "NUM_EXT_CONF_UN_EU" CHAR(50));


CREATE INDEX "CFDI_COMEXTCOMK001" ON "CFDI_COMEXTCOMPANY"("NAME_COMPANY", "RFC");

CREATE TABLE "CFDI_COMEXT_OE_SO"(
 "ORDER_NO" CHAR(7) NOT NULL ,
 "MOTIVO_TRASLADO" CHAR(2),
 "TIPO_OPERACION" CHAR(1),
 "CLAVE_PEDIMENTO" CHAR(2),
 "CERTDEORIGEN" CHAR(50),
 "NO_CERTDEORIGEN" CHAR(100),
 "INCOTERM" CHAR(3),
 "NO_EXP_CON_UN_EU" CHAR(100),
 "SUBDIVISION" CHAR(50),
 "OBSERVACIONES" CHAR(255),
 "P_TAX_ID" CHAR(50),
 "P_RES_FISCAL" CHAR(3),
 "VAL_UNIT_ADUANA" CHAR(100),
 "CANTIDAD_ADUANA" CHAR(100));

CREATE INDEX "CFDI_COMEXT_OE_SOK00" USING 0 ON "CFDI_COMEXT_OE_SO"("ORDER_NO", "CLAVE_PEDIMENTO", "NO_CERTDEORIGEN", "NO_EXP_CON_UN_EU");

CREATE TABLE "CFDI_COMEXT_INV"(
 "PART" CHAR(23) NOT NULL ,
 "FRACCION_ARANCELARIA" CHAR(8),
 "UNIDAD_ADUANA" CHAR(2),
 "MARCA" CHAR(100));

CREATE INDEX "CFDI_COMEXT_INV" USING 0 ON "CFDI_COMEXT_INV"("PART", "FRACCION_ARANCELARIA");

